import type { NextPage } from 'next'
import Head from "next/head"
import {Container, Heading} from "@chakra-ui/react"
import { Box } from "@chakra-ui/react"

const Sandbox: NextPage = () => {
  return (
      <>
          <Head>
              <title>Sandbox</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
              <Box bg="orange.300" w="100%" p={4} color="white">
                  <Heading>Sandbox</Heading>
              </Box>
              <Container py={8} maxW="container.lg">
                  aaaa
              </Container>
          </main>
      </>
  )
}

export default Sandbox
